version: '3'

services:
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build: /requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    ports:
    - 5000:5000
    restart: on-failure